=== juandmelendezpe/proyects-XML-DTD-XSD/xfactura/factura.dtd
<!ATTLIST factura
    numero ID #REQUIRED
    fecha CDATA #REQUIRED>
<!ELEMENT factura (nref, fpago, emisor, receptor, concepto*, baseimponible, totaliva, total)>
<!ELEMENT nref (#PCDATA)>
<!ELEMENT fpago (#PCDATA)>
<!ELEMENT emisor (direccion, nif)>
<!ATTLIST emisor empresa CDATA #REQUIRED>
<!ELEMENT direccion (calle, numero, cp, localidad, provincia)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT receptor (direccion, nif)>
<!ATTLIST receptor empresa CDATA #REQUIRED>
<!ELEMENT concepto (cantidad, preciouni, iva, importe)>
<!ATTLIST concepto descripcion CDATA #REQUIRED>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT preciouni (#PCDATA)>
<!ELEMENT iva (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT baseimponible (#PCDATA)>
<!ELEMENT totaliva (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== juandmelendezpe/proyects-XML-DTD-XSD/xfactura/factura.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- DTD 2 puntos - XSD 8 puntos-->
<!-- En el XSD hay que definir los siguientes tipos de datos:
-tipoformapago: puede ser Contado o Plazos. (0,5 puntos)
-tipodecimalpositivo: Tiene que ser 0 o mayor y con un máximo de 2 decimales. (0,5 puntos)
-tiponif: Como cualquier DNI. (0,5 puntos)
-tipoiva: Solo puede tener los valores 4, 8 o 18 (0,5 puntos)
-tipocp: van del 10000 al 99999. (0,5 puntos)
-tiponref: 7 caracteres alfanuméricos. (0,5 puntos)
-->
<factura
numero="N3457-2011" fecha="2011-03-29" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="factura.xsd">
<!--<!DOCTYPE factura SYSTEM "factura.dtd">-->
<!--<factura numero="N3457-2011" fecha="2011-03-29"> -->
	<nref>123FE45</nref>
	<fpago>Contado</fpago>
	<emisor empresa="Electronica Milenio">
		<direccion>
			<calle>Avda las Vidrieras</calle>
			<numero>5</numero>
			<cp>45280</cp>
			<localidad>Olias del Rey</localidad>
			<provincia>Toledo</provincia>
		</direccion>
		<nif>Q-56435454O</nif>
	</emisor>
	<receptor empresa="Imagen La Mancha">
		<direccion>
			<calle>IV centenario</calle>
			<numero>56</numero>
			<cp>45003</cp>
			<localidad>Toledo</localidad>
			<provincia>Toledo</provincia>
		</direccion>
		<nif>K-22315547H</nif>
	</receptor>
	<concepto descripcion="Gafas Lectura">
		<cantidad>4</cantidad>
		<preciouni>30</preciouni>
		<iva>8</iva>
		<importe>129.50</importe>
	</concepto>
	<concepto descripcion="Revistas Componentes">
		<cantidad>10</cantidad>
		<preciouni>6</preciouni>
		<iva>4</iva>
		<importe>62.40</importe>
	</concepto>
	<concepto descripcion="TV LG 22">
		<cantidad>3</cantidad>
		<preciouni>250</preciouni>
		<iva>18</iva>
		<importe>885</importe>
	</concepto>
	<baseimponible>930</baseimponible>
	<totaliva>147</totaliva>
	<total>1077</total>
</factura>
