=== juandmelendezpe/proyects-XML-DTD-XSD/solicitud/solicitud.dtd
<!ELEMENT solicitud (solicitante+,actividad+,peticion+)>

<!ELEMENT solicitante (nombre*,anio*,telefono+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ELEMENT direccion (calle,numero,piso,letra)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT letra (#PCDATA)>

<!ELEMENT actividad (nombre,nivel)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>

<!ELEMENT peticion (#PCDATA)>

=== juandmelendezpe/proyects-XML-DTD-XSD/solicitud/solicitud.xml
<?xml version="1.0" encoding="UTF-8"?>
<solicitud xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="solicitud.xsd">
<!--<!DOCTYPE solicitud SYSTEM "solicitud.dtd">-->
<!--<solicitud>-->
	<solicitante>
		<nombre>Alberto Rodr√≠guez Alonso</nombre>
		<anio>2023</anio>
		<direccion>
			<calle>Avda. Reconquista</calle>
			<numero>12</numero>
			<piso>1</piso>
			<letra>D</letra>
		</direccion>
		<telefono>698227182</telefono>
		<telefono>925265789</telefono>
	</solicitante>
	<actividad>
		<nombre>Natacion</nombre>
		<nivel>3</nivel>
	</actividad>
	<peticion>C02</peticion>
	<peticion>D03</peticion>
	<peticion>A10</peticion>
</solicitud>
