=== juandmelendezpe/proyects-XML-DTD-XSD/biblioteca/biblioteca.dtd
<!ELEMENT biblioteca (libros,socios,prestamos)>
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo,autor+,ejemplar+)>
<!ATTLIST libro isbn ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ATTLIST autor nombre CDATA #REQUIRED> 
<!ELEMENT ejemplar (#PCDATA)>
<!ATTLIST ejemplar codigo ID #REQUIRED>
<!ELEMENT socios (socio+)>
<!ELEMENT socio (nombre,direccion?)>
<!ATTLIST socio dni CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT prestamos (prestamo+)>
<!ELEMENT prestamo (fecha)>
<!ATTLIST prestamo ejemplar CDATA #REQUIRED>
<!ATTLIST prestamo socio CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>

=== juandmelendezpe/proyects-XML-DTD-XSD/biblioteca/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
	<libros>
		<libro isbn="aa">
			<titulo>El Quijote</titulo>
			<autor nombre="Cervantes"/>
			<ejemplar codigo="aaa"/>
			<ejemplar codigo="aab"/>
			<ejemplar codigo="aac"/>
			<ejemplar codigo="aad"/>
		</libro>
		<libro isbn="bb">
			<titulo>La Colmena</titulo>
			<autor nombre="Cela"></autor>
			<autor nombre="Pulido"></autor>
			<ejemplar codigo="bba"></ejemplar>
			<ejemplar codigo="bbb"></ejemplar>
		</libro>
	</libros>
	<socios>
		<socio dni="aaaaa">
			<nombre>Paco</nombre>
			<direccion>C/ sdfvsdfsdf</direccion>
		</socio>
		<socio dni="bbbbb">
			<nombre>Ana</nombre>
		</socio>
		<socio dni="ccccc">
			<nombre>Javier</nombre>
		</socio>
	</socios>
	<prestamos>
		<prestamo ejemplar="aac" socio="bbbbb">
			<fecha>12/05/2014</fecha>
		</prestamo>
		<prestamo ejemplar="bba" socio="ccccc">
			<fecha>11/05/2014</fecha>
		</prestamo>
	</prestamos>
</biblioteca>
