=== juandmelendezpe/proyects-XML-DTD-XSD/rss/rss.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault ="qualified">
    <xs:element name="rss">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="channel" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="xmlnsatom" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="channel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="atomlink" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="href" type="xs:string" use="required" />
                        <xs:attribute name="rel" type="xs:string" use="required" />
                        <xs:attribute name="type" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="title" minOccurs="1" maxOccurs="1" />
                <xs:element name="link" minOccurs="1" maxOccurs="1" />
                <xs:element name="description" minOccurs="1" maxOccurs="1" />
                <xs:element name="language" minOccurs="1" maxOccurs="1"/>
                <xs:element name="copyright" minOccurs="1" maxOccurs="1" />
                <xs:element ref="image" minOccurs="1" maxOccurs="1" />
                <xs:element ref="item" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" minOccurs="1" maxOccurs="1" />
                <xs:element name="url" minOccurs="1" maxOccurs="1" />
                <xs:element name="link" minOccurs="1" maxOccurs="1" />
                <xs:element name="width" minOccurs="1" maxOccurs="1" />
                <xs:element name="height" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" minOccurs="1" maxOccurs="1" />
                <xs:element name="link" minOccurs="1" maxOccurs="1" />
                <xs:element name="guid" minOccurs="1" maxOccurs="1" />
                <xs:element name="description" minOccurs="1" maxOccurs="1" />
                <xs:element name="pubDate" minOccurs="1" maxOccurs="1" />
                <xs:element name="category" type="tipocategoria" minOccurs="1" maxOccurs="1">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipocategoria">
        <xs:simpleContent>
            <xs:extension base="tcategoria">
                <xs:attribute name="domain" type="xs:string" use="required"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="tcategoria">
        <xs:restriction base="xs:string">
            <xs:pattern value="PHP"/>
            <xs:pattern value="JAVA"/>
            <xs:pattern value="REACT"/>
        </xs:restriction>
    </xs:simpleType>
    
    

</xs:schema>

=== juandmelendezpe/proyects-XML-DTD-XSD/rss/rss.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<rss version="2.0" xmlnsatom="http://www.w3.org/2005/Atom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rss.xsd">
	<channel>
		<atomlink href="http://www.electronica2000.com/canal/rss.xml" rel="self" type="application/rss+xml"/>
		<title>Título de blog o sitio</title>
		<link>http://www.dominio.com</link>
		<description>Descripción del blog o sitio</description>
		<language>es-ES</language>
		<copyright>todos los derechos reservados</copyright>
		<image>
			<title>Título de blog o sitio</title>
			<url>http://www.dominio.com/imagenes/logo.gif</url>
			<link>http://www.dominio.com</link>
			<width>100</width>
			<height>50</height>
		</image>
		<item>
			<title>Título del artículo</title>
			<link>http://www.dominio.com/documento-xml.php</link>
			<guid>http://www.dominio.com/documento-xml.php</guid>
			<description>Breve descripción del tema</description>
			<pubDate>Wed, 27 Oct 2010 07:15:00 GMT+1</pubDate>
			<category domain="http://www.dominio.com/php/">PHP</category>
		</item>
	</channel>
</rss>
